<script setup lang="ts">
	import { UiButton, UiInput } from "@dv.net/ui-kit/dist";
	import { storeToRefs } from "pinia";
	import { useAuthStore } from "@dv-admin/stores/auth";
	import { computed, toRefs } from "vue";
	import { useHotWalletsStore } from "@dv-admin/stores/hotWallets";
	import GlobalInput from "@dv-admin/components/ui/globalInput/GlobalInput.vue";

	const { userData2Fa, verificationCode2Fa, isCodeEntryMode } = storeToRefs(useAuthStore());
	const { postUser2FaChange } = useAuthStore();
	const { getWalletKeys, getWalletSeeds } = useHotWalletsStore();

	type RequestType = "seeds" | "keys";

	const props = withDefaults(defineProps<{ isCheckCode?: boolean; type?: RequestType }>(), {
		isCheckCode: false
	});
	const { isCheckCode, type } = toRefs(props);

	const isDisabled = computed<boolean>(() => !verificationCode2Fa.value);

	const handleSendCode = async () => {
		try {
			if (isCheckCode.value) {
				if (type.value === "seeds") await getWalletSeeds();
				if (type.value === "keys") await getWalletKeys();
			} else {
				await postUser2FaChange();
			}
		} catch (error: any) {
			console.error(error);
		}
	};
</script>

<template>
	<global-input class="code" title="Enter the code generated by your application">
		<form @submit.prevent="handleSendCode" class="code__form">
			<ui-input
				id="totp"
				name="totp"
				autocomplete="one-time-code"
				type="tel"
				v-model="verificationCode2Fa"
				:placeholder="$t('6-digit 2FA-code')"
				size="lg"
			/>
			<div v-if="isCheckCode" class="code__actions">
				<ui-button native-type="submit" mode="neutral" size="xl" :disabled="isDisabled">
					{{ $t("Send code") }}
				</ui-button>
			</div>
			<div v-else class="code__actions">
				<ui-button type="tertiary" size="xl" @click="isCodeEntryMode = false"> {{ $t("Cancel.noun") }} </ui-button>
				<ui-button native-type="submit" mode="neutral" size="xl" :disabled="isDisabled">
					{{ userData2Fa.is_confirmed ? $t("Disable") : $t("Turn on") }}
				</ui-button>
			</div>
		</form>
	</global-input>
</template>

<style scoped lang="scss">
	.code {
		width: 100%;
		display: flex;
		flex-direction: column;
		&__form {
			display: flex;
			align-items: center;
			gap: 12px;
		}
		&__actions {
			display: flex;
			align-items: center;
			gap: 4px;
		}
	}
</style>
