export const ALL_STATUSES: Record<string, string> = {
	completed: "Success",
	success: "Success",
	failed: "Error",
	new: "In progress",
	pending: "In progress",
	in_progress: "In progress",
	unconfirmed: "Unconfirmed",
	frozen: "Frozen",
	processing: "In processing",
	in_mempool: "In mempool",
	canceled: "Canceled",
	recovery: "Recovery",
	validate_request: "Confirm request",
	sending: "Transfer",
	waiting_in_mempool: "Pending in mempool",
	waiting_for_the_first_confirmation: "Waiting for first confirmation",
	waiting_confirmations: "Awaiting confirmation",
	send_success_event: "Send a successful event",
	check_activate_wallet: "Check wallet activation",
	activate_wallet: "Activate wallet",
	waiting_activate_confirmations: "Awaiting activation confirmation",
	before_sending_check_transfer_kind: "Before sending check transfer kind",
	send_trx_for_burn: "Burn TRX",
	waiting_send_trx_for_burn_confirmations: "Awaiting TRX burn confirmation",
	delegate_resources: "Resource delegation",
	waiting_delegate_confirmations: "Waiting for delegation confirmations",
	after_sending_check_transfer_kind: "After sending check transfer kind",
	reclaim_resources: "Reclaim resources",
	waiting_reclaim_resources_confirmations: "Waiting for resource recovery confirmation",
	send_eth_for_burn: "Send ETH for burn",
	waiting_send_eth_for_burn_confirmations: "Waiting for ETH burn confirmations"
};

export const ALL_MODE_TAG: Record<string, string> = {
	completed: "positive",
	success: "positive",
	failed: "negative",
	canceled: "warning",
	unconfirmed: "warning",
	frozen: "warning",
	recovery: "accent",
	new: "accent",
	pending: "accent",
	in_progress: "accent",
	processing: "accent",
	in_mempool: "accent",
	validate_request: "accent",
	sending: "accent",
	waiting_in_mempool: "accent",
	waiting_for_the_first_confirmation: "accent",
	waiting_confirmations: "accent",
	send_success_event: "positive",
	check_activate_wallet: "accent",
	activate_wallet: "accent",
	waiting_activate_confirmations: "accent",
	before_sending_check_transfer_kind: "accent",
	send_trx_for_burn: "accent",
	waiting_send_trx_for_burn_confirmations: "accent",
	delegate_resources: "accent",
	waiting_delegate_confirmations: "accent",
	after_sending_check_transfer_kind: "accent",
	reclaim_resources: "accent",
	waiting_reclaim_resources_confirmations: "accent",
	send_eth_for_burn: "accent",
	waiting_send_eth_for_burn_confirmations: "accent"
};
