export enum STORE_VERIFICATION_STATUS {
	PENDING = "PENDING",
	SUCCESS = "SUCCESS",
	REJECTED = "REJECTED"
}

export const STORE_VERIFICATION_STATUS_LABELS: Record<STORE_VERIFICATION_STATUS, string> = {
	[STORE_VERIFICATION_STATUS.PENDING]: "Pending",
	[STORE_VERIFICATION_STATUS.SUCCESS]: "Verified",
	[STORE_VERIFICATION_STATUS.REJECTED]: "Rejected"
};

export const STORE_VERIFICATION_STATUS_MODES: Record<
	STORE_VERIFICATION_STATUS,
	"warning" | "positive" | "negative"
> = {
	[STORE_VERIFICATION_STATUS.PENDING]: "warning",
	[STORE_VERIFICATION_STATUS.SUCCESS]: "positive",
	[STORE_VERIFICATION_STATUS.REJECTED]: "negative"
};

export const STORE_ACTION_FEEDBACK_MS = 2000;
export const STORE_ACTION_FEEDBACK_ANIMATION_MS = 280;
