<script setup lang="ts">
	import { UiButton, UiCopyText, UiInput } from "@dv.net/ui-kit/dist";
	import IconGoogle from "@dv-admin/components/icons/profile/IconGoogle.vue";
	import { storeToRefs } from "pinia";
	import { useAuthStore } from "@dv-admin/stores/auth";
	import { computed, ref } from "vue";
	import QrcodeVue from "qrcode.vue";
	import BlockSection from "@dv-admin/components/ui/BlockSection/BlockSection.vue";

	const { user, userData2Fa, isCodeEntryMode, verificationCode2Fa, isLoading2fa } = storeToRefs(useAuthStore());
	const { postUser2FaChange } = useAuthStore();

	const isEnterCodeManually = ref<boolean>(false);

	const isDisabledBtn = computed<boolean>(() => verificationCode2Fa.value.length < 6);
	const linkQrCode = computed<string | null>(() => {
		if (!user.value || !userData2Fa.value?.secret) return null;
		return `otpauth://totp/DV.net:${user.value.email}?secret=${userData2Fa.value.secret}&issuer=DV.net`;
	});

	const handleCancelSend = () => {
		isCodeEntryMode.value = false;
		verificationCode2Fa.value = "";
	};
</script>

<template>
	<block-section v-if="!isCodeEntryMode" class="authentication">
		<div class="authentication__logo">
			<icon-google />
		</div>
		<div class="authentication__content">
			<span class="authentication__title"> Google Authenticator </span>
			<span class="authentication__text">
				{{ $t("Convenient tool for 2FA codes") }}
			</span>
		</div>
		<ui-button type="secondary" size="sm" @click="isCodeEntryMode = true">
			{{ userData2Fa?.is_confirmed ? $t("Disable") : $t("Connect") }}
		</ui-button>
	</block-section>
	<!-- Form for code generation	-->
	<block-section v-else class="connect">
		<div v-if="!userData2Fa?.is_confirmed" class="connect__top">
			<h2 class="global-title-h3">{{ $t("Two-factor authentication") }}</h2>
			<p class="connect__text">
				{{ $t(isEnterCodeManually ? "Enter the text code into your app" : "Scan the QR code in your app") }}
			</p>
		</div>
		<div v-if="!userData2Fa?.is_confirmed" class="connect__code">
			<div v-if="isEnterCodeManually" class="flex flex-y-center gap-8">
				<p class="connect__code-code">
					{{ userData2Fa?.secret?.match(/.{1,4}/g)?.join(" ") ?? "" }}
				</p>
				<ui-copy-text :copied-text="userData2Fa.secret" />
			</div>
			<div v-else>
				<qrcode-vue v-if="linkQrCode" :value="linkQrCode" :size="122" render-as="svg" level="Q" />
				<div v-else>{{ $t("There is no secret code") }}</div>
			</div>
			<span v-if="linkQrCode" class="connect__code-toggle" @click="isEnterCodeManually = !isEnterCodeManually">
				{{ $t(isEnterCodeManually ? "Click here to scan the QR code" : "Click here to enter the code manually") }}
			</span>
		</div>
		<form @submit.prevent="postUser2FaChange" class="flex flex-column">
			<p v-if="userData2Fa.is_confirmed" class="connect__text mb-16">
				{{ $t("Enter the code generated by your application") }}
			</p>
			<ui-input
				id="totp"
				name="totp"
				autocomplete="one-time-code"
				type="tel"
				v-model="verificationCode2Fa"
				:placeholder="'2FA-' + $t('code')"
				size="md"
				class="mb-24"
			/>
			<div class="flex flex-y-center gap-16">
				<ui-button native-type="submit" mode="neutral" size="lg" :loading="isLoading2fa" :disabled="isDisabledBtn">
					{{ userData2Fa.is_confirmed ? $t("Disable") : $t("Turn on") }}
				</ui-button>
				<ui-button type="tertiary" size="lg" @click="handleCancelSend">
					{{ $t("Cancel.noun") }}
				</ui-button>
			</div>
		</form>
	</block-section>
</template>

<style scoped lang="scss">
	.authentication {
		display: flex;
		align-items: center;
		gap: 16px;
		&__logo {
			display: flex;
			justify-content: center;
			align-items: center;
			width: 40px;
			height: 40px;
			border-radius: 5.714px;
			border: 1px solid $grey-light;
		}
		&__content {
			flex-grow: 1;
			display: flex;
			flex-direction: column;
			gap: 4px;
		}
		&__title {
			color: $black;
			font-size: 16px;
			font-weight: 500;
			line-height: 20px;
		}
		&__text {
			color: $secondary;
			font-size: 12px;
			font-weight: 400;
			line-height: 16px;
		}
	}
	.connect {
		display: flex;
		flex-direction: column;
		gap: 24px;
		&__top {
			display: flex;
			flex-direction: column;
			gap: 16px;
		}
		&__text {
			color: $black;
			font-size: 14px;
			font-weight: 400;
			line-height: 20px;
		}
		&__code {
			display: flex;
			flex-direction: column;
			gap: 16px;
			&-code {
				color: $black;
				font-size: 20px;
				font-weight: 600;
				line-height: 24px;
			}
			&-toggle {
				color: $blue;
				font-size: 12px;
				font-weight: 500;
				line-height: 16px;
				width: max-content;
				border-bottom: 1px solid transparent;
				@media (hover: hover) {
					&:hover {
						cursor: pointer;
						border-bottom: 1px solid;
					}
				}
			}
		}
	}
</style>
