<script setup lang="ts">
	import { UiButton, UiCopyText, UiInput } from "@dv.net/ui-kit/dist";
	import { UiTooltip } from "@dv.net/ui-kit";
	import IconGoogle from "@dv-admin/components/icons/profile/IconGoogle.vue";
	import { storeToRefs } from "pinia";
	import { useAuthStore } from "@dv-admin/stores/auth";
	import { computed, ref } from "vue";
	import QrcodeVue from "qrcode.vue";
	import BlockSection from "@dv-admin/components/ui/BlockSection/BlockSection.vue";
	import { postApiUser2FaResetInit } from "@dv-admin/services/api/auth.ts";
	import { useNotifications } from "@shared/utils/composables/useNotifications.ts";
	import { useI18n } from "vue-i18n";
	import { formatDate } from "@dv-admin/utils/helpers/dateParse.ts";

	const { notify } = useNotifications();
	const { t } = useI18n();

	const authStore = useAuthStore();
	const {
		user,
		userData2Fa,
		isCodeEntryMode,
		verificationCode2Fa,
		isLoading2fa,
		isTwoFaResetExpiresAt,
		isLoadingDelete2Fa
	} = storeToRefs(authStore);
	const { postUser2FaChange, getUser, getInfoUser2Fa, deleteUser2FaReset } = authStore;

	const isEnterCodeManually = ref<boolean>(false);
	const isLoading2FaResetInit = ref<boolean>(false);

	const isDisabledBtn = computed<boolean>(() => verificationCode2Fa.value.length < 6);

	const linkQrCode = computed<string | null>(() => {
		if (!user.value || !userData2Fa.value?.secret) return null;
		return `otpauth://totp/DV.net:${user.value.email}?secret=${userData2Fa.value.secret}&issuer=DV.net`;
	});

	const handleCancelSend = () => {
		isCodeEntryMode.value = false;
		verificationCode2Fa.value = "";
	};

	const postUser2FaResetInit = async () => {
		try {
			isLoading2FaResetInit.value = true;
			await postApiUser2FaResetInit();
			await Promise.all([getInfoUser2Fa(), getUser()]);
			if (user.value?.two_fa_reset_expires_at) {
				notify(
					t("You’ve started resetting your two-factor authentication. It will be completed on {date}", {
						date: formatDate(user.value.two_fa_reset_expires_at)
					}),
					"success"
				);
			}
		} catch (error: any) {
			console.error(error);
		} finally {
			isLoading2FaResetInit.value = false;
		}
	};
</script>

<template>
	<block-section v-if="!isCodeEntryMode" class="authentication">
		<div class="authentication__logo">
			<icon-google />
		</div>
		<div class="authentication__content">
			<span class="authentication__title"> Google Authenticator </span>
			<span class="authentication__text">
				{{ $t("Convenient tool for 2FA codes") }}
			</span>
		</div>
		<div class="flex flex-y-center gap-8">
			<ui-button type="secondary" size="sm" @click="isCodeEntryMode = true">
				{{ userData2Fa?.is_confirmed ? $t("Disable") : $t("Connect") }}
			</ui-button>
			<div v-if="userData2Fa?.is_confirmed">
				<ui-button
					v-if="isTwoFaResetExpiresAt"
					type="primary"
					:loading="isLoadingDelete2Fa"
					size="sm"
					@click="deleteUser2FaReset($t('You have cancelled the 2FA reset'))"
				>
					{{ $t("Cancel 2FA reset") }}
				</ui-button>
				<ui-tooltip
					v-else
					mode="dark"
					:title="$t('Start a 2FA reset')"
					:text="$t('After initiating the 2FA reset, a 15-day waiting period will begin')"
				>
					<ui-button type="negative" :loading="isLoading2FaResetInit" size="sm" @click="postUser2FaResetInit">
						{{ $t("Reset") }}
					</ui-button>
				</ui-tooltip>
			</div>
		</div>
	</block-section>
	<!-- Form for code generation	-->
	<block-section v-else class="connect">
		<div v-if="!userData2Fa?.is_confirmed" class="connect__top">
			<h2 class="global-title-h3">{{ $t("Two-factor authentication") }}</h2>
			<p class="connect__text">
				{{ $t(isEnterCodeManually ? "Enter the text code into your app" : "Scan the QR code in your app") }}
			</p>
		</div>
		<div v-if="!userData2Fa?.is_confirmed" class="connect__code">
			<div v-if="isEnterCodeManually" class="flex flex-y-center gap-8">
				<p class="connect__code-code">
					{{ userData2Fa?.secret?.match(/.{1,4}/g)?.join(" ") ?? "" }}
				</p>
				<ui-copy-text :copied-text="userData2Fa.secret" />
			</div>
			<div v-else>
				<qrcode-vue v-if="linkQrCode" :value="linkQrCode" :size="122" render-as="svg" level="Q" />
				<div v-else>{{ $t("There is no secret code") }}</div>
			</div>
			<span v-if="linkQrCode" class="connect__code-toggle" @click="isEnterCodeManually = !isEnterCodeManually">
				{{ $t(isEnterCodeManually ? "Click here to scan the QR code" : "Click here to enter the code manually") }}
			</span>
		</div>
		<form @submit.prevent="postUser2FaChange" class="flex flex-column">
			<p v-if="userData2Fa.is_confirmed" class="connect__text mb-16">
				{{ $t("Enter the code generated by your application") }}
			</p>
			<ui-input
				id="totp"
				name="totp"
				autocomplete="one-time-code"
				type="tel"
				v-model="verificationCode2Fa"
				:placeholder="'2FA-' + $t('code')"
				size="md"
				class="mb-24"
			/>
			<div class="flex flex-y-center gap-16">
				<ui-button native-type="submit" mode="neutral" size="lg" :loading="isLoading2fa" :disabled="isDisabledBtn">
					{{ userData2Fa.is_confirmed ? $t("Disable") : $t("Turn on") }}
				</ui-button>
				<ui-button type="tertiary" size="lg" @click="handleCancelSend">
					{{ $t("Cancel.noun") }}
				</ui-button>
			</div>
		</form>
	</block-section>
</template>

<style scoped lang="scss">
	.authentication {
		display: flex;
		align-items: center;
		gap: 16px;
		&__logo {
			display: flex;
			justify-content: center;
			align-items: center;
			width: 40px;
			height: 40px;
			border-radius: 5.714px;
			border: 1px solid $grey-light;
		}
		&__content {
			flex-grow: 1;
			display: flex;
			flex-direction: column;
			gap: 4px;
		}
		&__title {
			color: $black;
			font-size: 16px;
			font-weight: 500;
			line-height: 20px;
		}
		&__text {
			color: $secondary;
			font-size: 12px;
			font-weight: 400;
			line-height: 16px;
		}
	}
	.connect {
		display: flex;
		flex-direction: column;
		gap: 24px;
		&__top {
			display: flex;
			flex-direction: column;
			gap: 16px;
		}
		&__text {
			color: $black;
			font-size: 14px;
			font-weight: 400;
			line-height: 20px;
		}
		&__code {
			display: flex;
			flex-direction: column;
			gap: 16px;
			&-code {
				color: $black;
				font-size: 20px;
				font-weight: 600;
				line-height: 24px;
			}
			&-toggle {
				color: $blue;
				font-size: 12px;
				font-weight: 500;
				line-height: 16px;
				width: max-content;
				border-bottom: 1px solid transparent;
				@media (hover: hover) {
					&:hover {
						cursor: pointer;
						border-bottom: 1px solid;
					}
				}
			}
		}
	}
</style>
